-- MySQL Script generated by MySQL Workbench
-- Thu Jan  6 18:54:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lms` DEFAULT CHARACTER SET utf8 ;
USE `lms` ;

-- -----------------------------------------------------
-- Table `lms`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `role` ENUM('profosser', 'student', 'it') NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `created_by` INT NULL,
  `department_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_created_by_users_idx` (`created_by` ASC) ,
  INDEX `fk_users_departments1_idx` (`department_id` ASC) ,
  CONSTRAINT `fk_created_by_users`
    FOREIGN KEY (`created_by`)
    REFERENCES `lms`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `lms`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`courses` (
  `code` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `creadit_hours` INT NOT NULL,
  `seats_no` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `tuition` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_courses_profosser_id_idx` (`professor_id` ASC) ,
  CONSTRAINT `fk_courses_profosser_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `lms`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`course_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`course_students` (
  `reg_no` INT NOT NULL,
  `course_code` INT NOT NULL,
  `student_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `grade` DECIMAL(5,2) NULL,
  `pay` BIT NULL,
  `pay_date` DATETIME NULL,
  INDEX `fk_course_students_courses1_idx` (`course_code` ASC) ,
  PRIMARY KEY (`reg_no`),
  CONSTRAINT `fk_course_students_courses1`
    FOREIGN KEY (`course_code`)
    REFERENCES `lms`.`courses` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_students_users1`
    FOREIGN KEY (`student_id`)
    REFERENCES `lms`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`students_attendances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`students_attendances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reg_no` INT NOT NULL,
  `session_date` DATETIME NULL,
  `attended` BIT NULL COMMENT '0 == false\n1 == true',
  PRIMARY KEY (`id`),
  INDEX `fk_students_attendances_course_students1_idx` (`reg_no` ASC) ,
  CONSTRAINT `fk_students_attendances_course_students1`
    FOREIGN KEY (`reg_no`)
    REFERENCES `lms`.`course_students` (`reg_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
